services:
  
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    
  posgresql:
    image: "postgres:latest"
    container_name: "posgresql"
    environment:
      POSTGRES_USER: "dbadmin"
      POSTGRES_PASSWORD: "dbadmin"
      POSTGRES_DB: "travelticketdb"
    ports:
      - "5433:5432"
  
  serilog-seq:
    image: "datalust/seq:latest"
    container_name: "serilog-seq"
    ports:
      - "5341"
    environment:
      ACCEPT_EULA: "Y"
  
  keycloak:
    image: "quay.io/keycloak/keycloak:21.0.2"
    container_name: "keycloak"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command:
      - start-dev
    ports:
      - "6743:8080"